# Generated by Django 5.2.11 on 2026-02-14 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the record is active and visible', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('urls_to_crawl', models.JSONField(default=list, help_text='Target URLs for crawling')),
                ('urls_crawled', models.JSONField(default=list, help_text='Successfully crawled URLs')),
                ('urls_failed', models.JSONField(default=list, help_text='Failed URLs with error reasons')),
                ('raw_results', models.JSONField(blank=True, help_text='Raw crawl data from Crawl4AI', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crawl Session',
                'verbose_name_plural': 'Crawl Sessions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the record is active and visible', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price in USD', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('url', models.URLField(max_length=1000)),
                ('source_domain', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='All extracted data (specs, reviews, etc.)')),
                ('features', models.JSONField(default=list, help_text='List of product features')),
                ('llm_summary', models.TextField(blank=True, help_text='AI-generated summary', null=True)),
                ('llm_score', models.FloatField(blank=True, help_text='LLM ranking score (0-100)', null=True)),
                ('llm_pros', models.JSONField(default=list, help_text='AI-identified pros')),
                ('llm_cons', models.JSONField(default=list, help_text='AI-identified cons')),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='procurement.crawlsession')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-llm_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the record is active and visible', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('query_text', models.TextField(help_text="Natural language query (e.g., 'best wireless headphones under $200')")),
                ('parsed_intent', models.JSONField(blank=True, help_text='LLM-parsed intent with extracted entities', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if query failed', null=True)),
                ('user', models.ForeignKey(help_text='User who created this query', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Query',
                'verbose_name_plural': 'Product Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='crawlsession',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_sessions', to='procurement.productquery'),
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the record is active and visible', verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('llm_reasoning', models.TextField(help_text='Chain-of-thought explanation for rankings')),
                ('llm_recommendation', models.TextField(blank=True, help_text='AI recommendation summary', null=True)),
                ('ranking_criteria', models.JSONField(default=dict, help_text='Criteria used for ranking (price, features, reviews, etc.)')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='procurement.productquery')),
            ],
            options={
                'verbose_name': 'Comparison Result',
                'verbose_name_plural': 'Comparison Results',
            },
        ),
        migrations.CreateModel(
            name='ProductRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Position in ranking (1 = best)')),
                ('reasoning', models.TextField(blank=True, help_text="Specific reasoning for this product's rank")),
                ('score_breakdown', models.JSONField(default=dict, help_text='Detailed scoring (price_score, feature_score, etc.)')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='procurement.comparisonresult')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.product')),
            ],
            options={
                'verbose_name': 'Product Ranking',
                'verbose_name_plural': 'Product Rankings',
                'ordering': ['rank'],
                'unique_together': {('comparison', 'rank')},
            },
        ),
    ]
